#!/usr/bin/env python3
"""Generate Verilator-friendly behavioral Verilog models from a liberty file.

The official ASAP7 behavioral models use UDP primitives (altos_dff) that
Verilator cannot compile, so for gate-level activity simulation we derive
zero-delay models straight from the liberty function/ff/latch groups.
Covers: combinational cells, DFF (any clock polarity, async clear/preset),
latches, scan flops, ICGs (latch + AND per the liberty groups), tie cells.

Usage: gen_sim_models.py out.v in1.lib [in2.lib ...]
"""
import re
import sys


def parse_cells(text):
    cells = []
    for m in re.finditer(r'\bcell\(([^)]+)\)\s*\{', text):
        name = m.group(1)
        depth, j = 0, m.end() - 1
        while j < len(text):
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        cells.append((name, text[m.start():j + 1]))
    return cells


def attr(body, name):
    m = re.search(r'\b%s\s*:\s*"?([^";]+?)"?\s*;' % name, body)
    return m.group(1).strip() if m else None


def group_body(body, header_re):
    m = re.search(header_re, body)
    if not m:
        return None, None
    depth, j = 0, m.end() - 1
    while j < len(body):
        if body[j] == '{':
            depth += 1
        elif body[j] == '}':
            depth -= 1
            if depth == 0:
                break
        j += 1
    return m, body[m.start():j + 1]


def lib2v(expr):
    e = expr.strip()
    e = e.replace('*', '&').replace('+', '|')
    e = re.sub(r"([A-Za-z_][A-Za-z0-9_]*)'", r'(!\1)', e)  # postfix negation
    return e


def single_literal(expr):
    """Return (pin, active_high) if expr is a bare or negated single pin."""
    e = expr.strip().strip('()').strip()
    m = re.fullmatch(r'!\s*\(?([A-Za-z_][A-Za-z0-9_]*)\)?', e)
    if m:
        return m.group(1), False
    if re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', e):
        return e, True
    return None, None


def gen_cell(name, body):
    pins = []  # (pin, dir, function)
    for pm in re.finditer(r'\bpin\(([^)]+)\)\s*\{', body):
        _, pb = group_body(body[pm.start():], r'\bpin\(')
        pins.append((pm.group(1), attr(pb, 'direction'), attr(pb, 'function')))
    if not pins:
        return None

    inputs = [p for p, d, _ in pins if d == 'input']
    outputs = [(p, f) for p, d, f in pins if d == 'output']
    lines = ['module %s (%s);' % (name, ', '.join([p for p, _ in outputs] + inputs))]
    for p, _ in outputs:
        lines.append('  output %s;' % p)
    for p in inputs:
        lines.append('  input %s;' % p)

    state = []
    fm, fb = group_body(body, r'\bff\(([^)]+)\)\s*\{')
    lm, lb = group_body(body, r'\blatch\(([^)]+)\)\s*\{')
    if fb:
        iq, iqn = [s.strip() for s in fm.group(1).split(',')]
        clk, next_state = attr(fb, 'clocked_on'), attr(fb, 'next_state')
        clear, preset = attr(fb, 'clear'), attr(fb, 'preset')
        cpin, cah = single_literal(clk)
        edge = 'posedge' if cah else 'negedge'
        sens = ['%s %s' % (edge, cpin)]
        conds = []
        for aexpr, val in ((clear, '0'), (preset, '1')):
            if aexpr:
                apin, aah = single_literal(aexpr)
                sens.append('%s %s' % ('posedge' if aah else 'negedge', apin))
                conds.append('if (%s) %s <= 1\'b%s;' % (lib2v(aexpr), iq, val))
        lines.append('  reg %s;' % iq)
        lines.append('  wire %s = !%s;' % (iqn, iq))
        lines.append('  always @(%s)' % ' or '.join(sens))
        stmt = '%s <= %s;' % (iq, lib2v(next_state))
        for c in reversed(conds):
            stmt = c + ' else ' + stmt
        lines.append('    ' + stmt)
        state += [iq, iqn]
    if lb:
        iq, iqn = [s.strip() for s in lm.group(1).split(',')]
        en, din = attr(lb, 'enable'), attr(lb, 'data_in')
        lines.append('  reg %s;' % iq)
        lines.append('  wire %s = !%s;' % (iqn, iq))
        lines.append('  /* verilator lint_off LATCH */')
        lines.append('  always @(*) if (%s) %s = %s;' % (lib2v(en), iq, lib2v(din)))
        lines.append('  /* verilator lint_on LATCH */')
        state += [iq, iqn]

    for p, f in outputs:
        if f is None:
            return None  # can't model an output without a function
        f = f.strip()
        if f in ('0', '1'):
            lines.append('  assign %s = 1\'b%s;' % (p, f))
        else:
            lines.append('  assign %s = %s;' % (p, lib2v(f)))
    lines.append('endmodule')
    return '\n'.join(lines)


def main():
    out, libs = sys.argv[1], sys.argv[2:]
    chunks = ['// Generated by gen_sim_models.py from: %s' % ' '.join(libs),
              '// Zero-delay behavioral models for gate-level activity simulation.',
              '/* verilator lint_off UNOPTFLAT */',
              '/* verilator lint_off UNUSEDSIGNAL */']
    n, skipped = 0, []
    for lib in libs:
        for name, body in parse_cells(open(lib).read()):
            v = gen_cell(name, body)
            if v is None:
                skipped.append(name)
            else:
                chunks.append(v)
                n += 1
    open(out, 'w').write('\n\n'.join(chunks) + '\n')
    print('wrote %s: %d cells modeled, %d skipped%s'
          % (out, n, len(skipped), (': ' + ' '.join(skipped)) if skipped else ''))


if __name__ == '__main__':
    main()
